baseURL: "https://www.pybamm.org"
languageCode: "en-us"
title: "PyBaMM" # site title
theme: scientific-python-hugo-theme
relativeURLs: true
DefaultContentLanguage: en
disableKinds: ["term", "taxonomy"]
enableEmoji: true
enableInlineShortcodes: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

params:
  title: PyBaMM Team # for copyright
  description: "PyBaMM (Python Battery Mathematical Modelling) is an open-source battery simulation package written in Python."

  images:
    - /images/pybamm_icon.png

  font:
    name: "Lato"
    # sizes: [400, 900]

  # plausible: analytics (TODO)

  style:
    vars:
      highlightColor: "#004811"
      menuHighlightColor: "#5CA038"

  navbarlogo:
    image: pybamm_icon.svg
    altText: The PyBaMM logo, with a battery of cells with the electrodes stacked in the standard Python blue and yellow colours
    text: PyBaMM
    link: /

  hero:
    title: PyBaMM
    subtitle: Fast and flexible physics-based battery models in Python for open science
    buttontext: View releases
    buttonlink: https://github.com/pybamm-team/PyBaMM/releases
    image: pybamm_icon.svg

  navbar:
    - title: Home
      url: /

    - title: News
      url: /news/

    - title: Training
      url: /training/

    - title: Getting started
      url: /get-started/

    - title: Contact
      url: /contact/

    - title: Wiki
      url: /wiki/

    - title: Examples
      url: https://github.com/pybamm-team/PyBaMM/tree/develop/examples/
      is_external: true

    - title: Documentation
      url: https://pybamm.readthedocs.io/
      # To be configured to https://docs.pybamm.org/
      is_external: true

    - title: Source code
      url: https://www.github.com/pybamm-team/PyBaMM/
      is_external: true

    - title: Publications
      url: /publications/

  # Grid of features
  keyfeatures:
    features:

      - title: Extensive
        text: PyBaMM comes with a comprehensive library of battery models, including the Doyle-Fuller-Newman model
              and the Single Particle Model.

      - title: State-of-the-art
        text: PyBaMM provides efficient, robust, and accurate simulations of battery behaviour, including demanding
          drive cycles.

      - title: Open-source
        text: Community-driven model development ensures PyBaMM remains at the cutting edge of battery modelling.

  footer:
    # Visibility is low with the current font and background colours
    logo: pybamm_logo.png
    socialmediatitle: ""
    socialmedia:
      - link: https://twitter.com/pybamm_/
        icon: twitter

      - link: https://www.youtube.com/@pybamm_/
        icon: youtube

      - link: https://github.com/pybamm-team/
        icon: github

    quicklinks:
      column1:
        title: ""
        links:
          - text: Install PyBaMM
            link: https://pybamm.readthedocs.io/en/latest/source/user_guide/installation/index.html/

          - text: Getting started
            link: /get-started/

          - text: Learn with examples
            link: https://github.com/pybamm-team/PyBaMM/tree/develop/examples/

          - text: Documentation
            link: https://pybamm.readthedocs.io/

          - text: Citing PyBaMM
            link: /publications/

      column2:
        title: ""
        links:
          - text: Contact
            link: /contact/

          - text: Get involved
            link: https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md/

          - text: Training
            link: /training/

          - text: News
            link: /news/

          - text: Roadmap
            link: https://github.com/pybamm-team/PyBaMM/wiki/Roadmap/

          # - text: Privacy
          #   link: /privacy/

      # column3:
      #   links:
